# Generated by Django 3.0.4 on 2020-06-03 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description_short', models.TextField(verbose_name='Короткое описание')),
                ('description_long', models.TextField(verbose_name='Длинное описание')),
                ('coordinates_lat', models.FloatField(verbose_name='Широта')),
                ('coordinates_lng', models.FloatField(verbose_name='Долгота')),
            ],
        ),
    ]
