# Generated by Django 3.0.4 on 2020-08-16 08:16

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_auto_20200815_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='long_description',
            field=tinymce.models.HTMLField(default='Впиши сюда вёрстку!', verbose_name='Длинное описание'),
        ),
    ]
