# Generated by Django 3.0.4 on 2020-06-04 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_place_test_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='test_field',
        ),
    ]
