# Generated by Django 3.0.3 on 2020-09-11 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_auto_20200816_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='tooltip_title',
            field=models.CharField(default='test', max_length=200, verbose_name='Сокращенное название'),
            preserve_default=False,
        ),
    ]
