# Generated by Django 3.0.3 on 2020-09-11 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_place_tooltip_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='tooltip_title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Сокращенное название'),
        ),
    ]
