# Generated by Django 3.0.4 on 2020-06-04 18:15

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_remove_place_test_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='text',
            field=tinymce.models.HTMLField(default=models.TextField(verbose_name='Длинное описание'), verbose_name='Длинное описание'),
        ),
    ]
