# Generated by Django 3.0.4 on 2020-06-04 18:19

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0006_place_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='description_long',
        ),
        migrations.AlterField(
            model_name='place',
            name='text',
            field=tinymce.models.HTMLField(default='Впиши вёрстку места, пожалуйста', verbose_name='Длинное описание'),
        ),
    ]
